#!/usr/bin/env python3
"""Build SKILLS-REGISTRY.md — an index of every installed Agent Skill.

Scans a skills directory for SKILL.md files, extracts the YAML frontmatter
(name + description), and writes a grouped Markdown registry.

Usage:
    python3 skills_registry.py [SKILLS_DIR]      (default: ~/skills)

Agents: when a task matches a skill's trigger text in the registry,
read that skill's SKILL.md and follow its instructions.
"""
import os
import re
import glob
import sys


def frontmatter(path):
    """Return (name, description) from a SKILL.md's YAML frontmatter."""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read(8000).replace("\r\n", "\n")
        m = re.match(r"^---\n(.*?)\n---", text, re.S)
        if not m:
            return None, None
        fm = m.group(1)
        name = re.search(r"^name:\s*(.+?)\s*$", fm, re.M)

        # description may be inline or a folded ( > / | ) block
        desc = ""
        lines = fm.splitlines()
        for i, line in enumerate(lines):
            if re.match(r"^description:", line):
                desc = line.split(":", 1)[1].strip()
                if desc in (">", "|", ">-", "|-", ""):
                    extra = []
                    for nxt in lines[i + 1:]:
                        if nxt.startswith((" ", "\t")) and nxt.strip():
                            extra.append(nxt.strip())
                        else:
                            break
                    desc = " ".join(extra)
                break
        desc = re.sub(r"\s+", " ", desc).strip().strip('"').strip("'")
        return (name.group(1).strip() if name else None), desc
    except Exception:
        return None, None


def build(skills_dir):
    groups = [
        ("Official — anthropics/skills", "skills"),
        ("reverse-skill — core modules (zhaoxuya520/reverse-skill)",
         "community/reverse-skill/skills"),
        ("reverse-skill — CTF competition pack",
         "community/reverse-skill/CTF-Sandbox-Orchestrator"),
        ("PixelRAG (StarTrail-org/PixelRAG)",
         "community/PixelRAG/plugin/skills"),
        ("SocratiCode (giancarloerra/SocratiCode)",
         "community/SocratiCode/skills"),
    ]

    out = [
        "# 🧰 Installed Skills Registry",
        "",
        "Auto-generated by `tools/skills_registry.py` — do not edit by hand.",
        f"Skills root: `{skills_dir}`",
        "",
        "**Routing rule:** when a task matches a skill's trigger text, open that",
        "skill's `SKILL.md` and follow its instructions/scripts.",
        "",
    ]
    total, counts = 0, []
    for group, sub in groups:
        base = os.path.join(skills_dir, sub)
        entries = []
        for smd in sorted(glob.glob(os.path.join(base, "**", "SKILL.md"),
                                    recursive=True)):
            name, desc = frontmatter(smd)
            if name:
                rel = os.path.relpath(smd, skills_dir)
                entries.append((name, desc[:160], rel))
        counts.append(len(entries))
        if not entries:
            continue
        out += [f"## {group} — {len(entries)} skills", "",
                "| Skill | Triggers on |", "|---|---|"]
        for name, desc, rel in entries:
            out.append(f"| [`{name}`]({rel}) | {desc.replace('|', '/')} |")
        out.append("")
        total += len(entries)

    out.append(f"**Total: {total} skills** "
               f"({' + '.join(map(str, counts))})")
    dest = os.path.join(skills_dir, "SKILLS-REGISTRY.md")
    with open(dest, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"registry: {total} skills -> {dest}")


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/skills")
    build(target)
